package(default_visibility = ["//visibility:public"])

exports_files(["only_keep_nv.lds"])


cc_library(
    name = "maca_hook",
    srcs = [
        "hook.cc",
    ],
    hdrs = [
        "hook.h",
    ],
    linkstatic = 1,
    deps = [
        "//xpu_timer",
        "//xpu_timer:macro",
        "//xpu_timer:manager",
        "//xpu_timer:util",
        "@apache_brpc//:bvar",
        "@maca//:maca_headers",
    ],
    copts = ["-g"],
    alwayslink = True,
)
