workspace(name="atorch")

load("//third_party/brpc:brpc_workspace.bzl", "brpc_workspace")
brpc_workspace();

load("//third_party/maca:maca_workspace.bzl", "maca_workspace")
maca_workspace();

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
http_archive(
    name = "com_github_jupp0r_prometheus_cpp",
    sha256 = "909d8162a1b676fefc3bef1634151947c64cd8ae37e43b36df357c7881aa8782",
    strip_prefix = "prometheus-cpp-1.2.4",
    urls = ["https://github.com/jupp0r/prometheus-cpp/archive/v1.2.4.zip"],
)
load("@com_github_jupp0r_prometheus_cpp//bazel:repositories.bzl", "prometheus_cpp_repositories")
prometheus_cpp_repositories()

http_archive(
    name = "curl",
    sha256 = "05fc17ff25b793a437a0906e0484b82172a9f4de02be5ed447e0cab8c3475add",
    strip_prefix = "curl-8.5.0",
    urls = [
        "https://github.com/curl/curl/releases/download/curl-8_5_0/curl-8.5.0.tar.gz",
        "https://curl.haxx.se/download/curl-8.5.0.tar.gz",
    ],
    build_file = "@com_github_jupp0r_prometheus_cpp//bazel:curl.BUILD", 
)

http_archive(
    name = "com_google_googletest",
    sha256 = "81964fe578e9bd7c94dfdb09c8e4d6e6759e19967e397dbea48d1c10e45d0df2",
    strip_prefix = "googletest-release-1.12.1",
    urls = [
        "file:///external/xpu_timer_dependency/gtest-release-1.12.1.tar.gz",
        "https://github.com/google/googletest/archive/release-1.12.1.tar.gz",
    ],
)
